### PR TITLE
Fix crash if authority is not uppercase in Wmts description

### PR DESCRIPTION
**Pull request by dobauer**
Hi,
I'm new to develop on Github. So I'm not completely aware of the procedures here.
But any ways here two little changes which I had to do to get BruTile working with our Wmts.

### CODE REVIEW

**Comment by pauldendulk** [comment]
The pull request procedure fine. 

Could you explain DimensionTimeTag change? I am not so familiar with the part myself.

**Comment by dobauer** [comment]
Our layer data is dependent on Time - so each Layer has a time parameter.
See WMS1.1.1, sect. 7.2.3
http://cite.opengeospatial.org/OGCTestData/wms/1.1.1/spec/wms1.1.1.html#wmsops.getcapabilities.response
it's an optional Parameter
It doesn't have actually no special usage here right now, but brutile hangs when it hits this Parameter -
may be it should be fix in way that all unknown parameters are ignored.
(some more info: https://wiki.earthdata.nasa.gov/pages/viewpage.action?pageId=14518214)

**Comment by pauldendulk** [comment]
When does this time parameter problem occur, when parsing the capabilities or when requesting a tile?

**Comment by dobauer** [comment]
The problem occurs when requesting a tile. So to be more precise - it's a optional parameter for the capabilities but if it is in the description it has to be used in the request - so my solution is actually not a good one!

**Comment by pauldendulk** [comment]
I suggest you send a pull request for the issue mentioned in the topic and add an issue for time parameter issue.

**Comment by dobauer** [comment]
The problem occurs when requesting a tile. So to be more precise - it's a optional parameter for the capabilities but if it is in the description it has to be used in the request - so my solution is actually not a good one!

**Pull request closed without merging**
