### PR TITLE
Switched BruTIle.MbTiles.Pcl to sqlite-net-pcl.1.2.1.

### PR DESCRIPTION
**Pull request by plamen-i**
Pull Request for #58.

Switched BruTIle.MbTiles.Pcl to sqlite-net-pcl.1.2.1. Switched also Test and Sample projects. Successfully ran Sample project.

Switched only Pcl version because other contains code based on System.Data.Sqlite. Maybe a future update - use Pcl version everywhere (I work this way and it works).

Used sqlite-net-pcl.1.2.1, because sqlite-net-pcl.1.3.x are .NET Standard based - a future update (maybe when VS 2017 released in March 2017) to the project required to target .NET Standard and also I did not tested it yet.

Best Regards

### CODE REVIEW

**Comment by pauldendulk** [comment]
Thanks! I have not looked at it yet but I do see that the build server is complaining. If you click the little red cross above it will take you to the build server log. Apparently there is a problem with this unit test: WhenKeepInMemoryIsUsedItShouldPreserveTilesThatMeetTheCondition. Could you take a look?

**Comment by plamen-i** [comment]
I saw the problem and checked it when created PR. But it is about test for MemoryCache class which is in BruTile, not BruTile.MbTiles.Pcl, where was my work. So I assumed that this is already known issue.

**Comment by pauldendulk** [comment]
okay, then I will have a look.

**Comment by pauldendulk** [comment]
I can not explain the test fail. I ran the tests again on the test server and they succeeded. They also succeed on my local machine (your fork and the original). There is no threading involved. I can not see why it would fail. It is clear it is not related to your patch, so I merged it. Thanks a lot!

**Comment by pauldendulk** [comment]
hey, you updated the nuspec as well, nice.

**Comment by pauldendulk** [comment]
I fixed the unit test issue with this commit: https://github.com/BruTile/BruTile/commit/588dd50ddfc7c54106dfc8bc32b05fa36eef0bc4

**Comment by plamen-i** [comment]
@pauldendulk Maybe its time to move to .Net Standard and also bump sqlite-net-pcl to latest version?

**Pull request merged**
