### PR TITLE
KnownTileSources: update Stamen URLs

### PR DESCRIPTION
**Pull request by janusw**
* use https URLs with new hostnames, as documented on maps.stamen.com
* the set of available subdomains still seems to be the same ('a' to 'd')
* note: the toner-lite layer is not documented on maps.stamen.com explicitly, but it still seems to work

### CODE REVIEW

**Comment by janusw** [comment]
Here is an example URL that I used for testing (with variations):
http://stamen-tiles-d.a.ssl.fastly.net/terrain/12/654/1583.png

**Comment by janusw** [comment]
Should fix #199, but I haven't verified that yet (will be much easier for me once #198 is merged).

**Comment by janusw** [comment]
I just rebased this to current master, in order to take advantage of #198. Will do some tests soon.

**Comment by janusw** [comment]
Alright, I tried the nupkg from https://github.com/BruTile/BruTile/actions/runs/3948252149#artifacts and can confirm that it works nicely and enables me to display the Stamen Terrain map on iOS and Android. I.e. this PR does fix #199 for me 🥳

**Review by pauldendulk — APPROVED** [review]
Thanks for taking care of this!

**Pull request merged**
